sonar.projectKey=anpr-inference-service
sonar.projectName=anpr-inference-service

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.10
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/.venv/**,**/.pytest_cache/**,**/.ruff_cache/**,**/__pycache__/**,**/data/**,**/docs/**,**/*.db,**/uv.lock,**/docker-compose.yml,**/Dockerfile
