name: "vehicle_detection_rt_detr"
platform: "pytorch_libtorch"

max_batch_size: 32

input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [3,640, 640]
  }
]

output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [300,19]
  }
]

dynamic_batching {
  preferred_batch_size: [4,8,16,32]
  max_queue_delay_microseconds: 100000
}

#GPU config
#instance_group [
#  {
#    kind: KIND_GPU
#    count: 1          # number of copies to keep on the card
#    gpus: [0]         # GPU IDs to target
#  }
#]

#CPU config
instance_group [
  { kind: KIND_CPU count: 1 }
]
